### PR TITLE
Background loading in thread

### PR DESCRIPTION
**Pull request by gwarmstrong**
This loads data in a background thread if loading data from a config file.

Depends on #88

### CODE REVIEW

**Comment by wasade** [comment]
That looks very clean!!! How's it on www-dev?

**Comment by gwarmstrong** [comment]
It works! some of the loading is still slow, and we are not using beta currently, but we have a working deployment with multiple datasets.

**Comment by wasade** [comment]
That's awesome! What happens if a request is made to an endpoint which depends on a background load?

**Comment by gwarmstrong** [comment]
It just looks like there is no data until the background load is complete

**Pull request merged**
